Update deploy-vm.yml

diff --git a/.github/workflows/deploy-vm.yml b/.github/workflows/deploy-vm.yml
--- a/.github/workflows/deploy-vm.yml
+++ b/.github/workflows/deploy-vm.yml
@@ -46,17 +46,17 @@ jobs:
     defaults:
       run:
         shell: bash
-        working-directory: ./terraform/deployments/goldenimage/uat
+        working-directory: ./terraform/deployments/goldenimage/${{ github.event.inputs.environment }}
 
     steps:
-    - name: Validate Input
-      run: |
-        choice="${{ github.event.inputs.environment }}"
-        if [[ "$choice" != "uat" && "$choice" != "stage" && "$choice" != "prod" ]]; then
-          echo "Invalid choice. Please select one of: uat, stage, prod"
-          exit 1
-        fi
-        echo "Selected Option: $choice"
+    #- name: Validate Input
+      #run: |
+        #choice="${{ github.event.inputs.environment }}"
+        #if [[ "$choice" != "uat" && "$choice" != "stage" && "$choice" != "prod" ]]; then
+          #echo "Invalid choice. Please select one of: uat, stage, prod"
+          #exit 1
+        #fi
+        #echo "Selected Option: $choice"
 
     # Checkout the repository to the GitHub Actions runner
     - name: Checkout
