Update deploy-vm.yml

diff --git a/.github/workflows/deploy-vm.yml b/.github/workflows/deploy-vm.yml
--- a/.github/workflows/deploy-vm.yml
+++ b/.github/workflows/deploy-vm.yml
@@ -40,16 +40,16 @@ jobs:
         working-directory: ./terraform/deployments/goldenimage/${{ github.event.inputs.environment }}
 
     steps:
-#     - name: Validate Input and set working directory
-#       run: |
-#         choice="${{ github.event.inputs.environment }}"
-#         if [[ "$choice" != "uat" && "$choice" != "stage" && "$choice" != "prod" ]]; then
-#           echo "Invalid choice. Please select one of: uat, stage, prod"
-#           exit 1
-#         else
-#           working-directory: ./terraform/deployments/goldenimage/$choice
-#         fi
-#         #echo "Selected Option: $choice"
+    - name: Validate Input and set working directory
+      run: |
+        choice="${{ github.event.inputs.environment }}"
+        #if [[ "$choice" != "uat" && "$choice" != "stage" && "$choice" != "prod" ]]; then
+          #echo "Invalid choice. Please select one of: uat, stage, prod"
+          #exit 1
+        #else
+          #working-directory: ./terraform/deployments/goldenimage/$choice
+        #fi
+        echo "Selected Option: $choice"
 
     # Checkout the repository to the GitHub Actions runner
     - name: Checkout
